#
#  Author: Hari Sekhon
#  Date: 2022-05-26 12:00:50 +0100 (Thu, 26 May 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Docker Build TeamCity

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - teamcity/Dockerfile
      - .github/workflows/docker_build_teamcity.yaml
  workflow_dispatch:
  #schedule:
  #  - cron: '0 2 * * *'

jobs:
  docker_build:
    name: Docker Build
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: |
      github.repository_owner == 'HariSekhon' &&
      (
        github.event_name == 'schedule' ||
        (
          github.ref_type == 'branch' &&
          ( github.ref_name == github.event.repository.default_branch || github.ref_name == 'docker' )
        )
      )
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo_tags: |
        ghcr.io/harisekhon/teamcity:latest
        harisekhon/teamcity:alpine
      context: teamcity
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
