#
#  Author: Hari Sekhon
#  Date: 2022-05-26 14:11:33 +0100 (Thu, 26 May 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Dockerfiles

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**Dockerfile**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**Dockerfile**'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  #schedule:
  #  - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_dockerfiles:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Check Dockerfiles
    uses: HariSekhon/GitHub-Actions/.github/workflows/dockerfiles.yaml@master
